// <auto-generated />
using JsonSample.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JsonSample.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250116210824_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JsonSample.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JsonSample.Entities.User", b =>
                {
                    b.OwnsMany("JsonSample.Entities.Article", "Articles", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Content")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId", "__synthesizedOrdinal");

                            b1.ToTable("Users");

                            b1.ToJson("Articles");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsMany("JsonSample.Entities.Comment", "Comments", b2 =>
                                {
                                    b2.Property<int>("ArticleUserId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Article__synthesizedOrdinal")
                                        .HasColumnType("int");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    b2.Property<string>("Content")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ArticleUserId", "Article__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Users");

                                    b2.WithOwner()
                                        .HasForeignKey("ArticleUserId", "Article__synthesizedOrdinal");
                                });

                            b1.Navigation("Comments");
                        });

                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
